#!/usr/bin/env python3

import contextlib
import sys


@contextlib.contextmanager
def safe_syspath():
    # The name of the script is the same as the name of the lib, so we
    # adjust the default sys.path.
    if sys.path[0] != '':
        if '' in sys.path:
            raise RuntimeError('unsupported sys.path')
        # nothing to do
        yield
        return

    sys.path.pop(0)
    try:
        yield
    finally:
        sys.path.insert(0, '')


with safe_syspath():
    try:
        from devbox.__main__ import parse_args, main
    except ImportError:
        # Try running from the project root.
        import os.path
        SCRIPTS_DIR = os.path.abspath(os.path.dirname(__file__))
        PROJECT_ROOT = os.path.dirname(SCRIPTS_DIR)
        sys.path.insert(0, PROJECT_ROOT)

        from devbox.__main__ import parse_args, main


if __name__ == '__main__':
    args = parse_args()
    sys.exit(main(args))
